bind 0.0.0.0
port 6379

# TFMS stream can spike with large payload bursts.
save ""
appendonly no

# Allow larger pubsub backlog before disconnecting websocket subscriber.
client-output-buffer-limit pubsub 1024mb 256mb 120
